[versions]
agp = "8.13.0"
androidTools = "31.13.0"
androidx-activity = "1.11.0"
androidx-appcompat = "1.7.1"
androidx-arch-core = "2.2.0"
androidx-compose-bom = "2025.11.00"
androidx-hilt = "1.3.0"
androidx-lifecycle = "2.9.4"
androidx-room = "2.8.3"
androidx-test = "1.7.0"
androidxLintGradle = "1.0.0-alpha05"
coilCompose = "2.7.0"
com-google-dagger = "2.57.2"
com-squareup-leakcanary = "2.14"
com-squareup-moshi = "1.15.2"
com-vanniktech-maven-publish = "0.34.0"
coreKtx = "1.17.0"
dokka = "2.1.0"
espresso-core = "3.7.0"
fragmentKtx = "1.8.9"
hilt = "2.57.2"
hiltExt = "1.3.0"
io-gitlab-arturbosch-detekt = "1.23.8"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21"
kotlinxSerializationCore = "1.9.0"
ksp = "2.3.2"
ktorClientCio = "3.3.2"
ktorClientContentNegotiation = "3.3.2"
ktorClientCore = "3.3.2"
ktorSerializationKotlinxJson = "3.3.2"
lifecycleViewmodelNav3 = "2.10.0-rc01"
lifecycleViewmodelNavigation3Android = "2.10.0-rc01"
material = "1.13.0"
material3AdaptiveNav3 = "1.3.0-alpha03"
materialIconsCore = "1.7.8"
nav3Core = "1.0.0-rc01"
orchestrator = "1.6.1"
org-jetbrains-kotlinx = "1.10.2"
org-jetbrains-kotlinx-binary-compatibility-validator = "0.18.1"
pagingCommon = "3.3.6"
pagingCompose = "3.3.6"
pagingTesting = "3.3.6"
se-eelde-toggles = "0.0.3"

[libraries]
android-tools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-arch-core-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-compose-material-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-ui-text = { module = "androidx.compose.ui:ui-text" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-core-splashscreen = "androidx.core:core-splashscreen:1.2.0"
androidx-fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "fragmentKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-hilt-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-lifecycle-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-lifecycle-viewmodel-navigation3-android = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3-android", version.ref = "lifecycleViewmodelNavigation3Android" }
androidx-lint-gradle = { module = "androidx.lint:lint-gradle", version.ref = "androidxLintGradle" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
# Note: The Material3 adaptive layouts library for Navigation 3 is currently
# only available in snapshot builds. Follow the instructions at androidx.dev to
# add the snapshot builds repository to your project.
androidx-material3-adaptive-navigation3 = { module = "androidx.compose.material3.adaptive:adaptive-navigation3", version.ref = "material3AdaptiveNav3" }
# Core Navigation 3 libraries
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingCommon" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingCompose" }
androidx-paging-testing = { module = "androidx.paging:paging-testing", version.ref = "pagingTesting" }
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-startup-startup-runtime = "androidx.startup:startup-runtime:1.2.0"
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-espresso-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-test-ext-truth = "androidx.test.ext:truth:1.7.0"
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "orchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
app-cash-licensee-licensee-gradle-plugin = "app.cash.licensee:licensee-gradle-plugin:1.14.1"
app-cash-turbine = "app.cash.turbine:turbine:1.2.1"
co-touchlab-kermit = "co.touchlab:kermit:2.0.8"
coil = { module = "io.coil-kt:coil", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
com-google-dagger = { module = "com.google.dagger:dagger", version.ref = "com-google-dagger" }
com-google-dagger-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "com-google-dagger" }
com-google-dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "com-google-dagger" }
com-google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "com-google-dagger" }
com-google-dagger-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
com-google-devtools-ksp-com-google-devtools-ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
com-google-gms-google-services = "com.google.gms:google-services:4.4.4"
com-slack-lint-compose-compose-lint-checks = "com.slack.lint.compose:compose-lint-checks:1.4.2"
com-slack-lint-slack-lint-checks = "com.slack.lint:slack-lint-checks:0.11.1"
com-squareup-kotlinpoet = "com.squareup:kotlinpoet:2.2.0"
com-squareup-leakcanary-leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "com-squareup-leakcanary" }
com-squareup-moshi = { module = "com.squareup.moshi:moshi", version.ref = "com-squareup-moshi" }
com-squareup-moshi-moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "com-squareup-moshi" }
com-squareup-okio = "com.squareup.okio:okio:3.16.2"
com-vanniktech-gradle-maven-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "com-vanniktech-maven-publish" }
hilt-ext-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltExt" }
io-gitlab-arturbosch-detekt-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "io-gitlab-arturbosch-detekt" }
io-gitlab-arturbosch-detekt-detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "io-gitlab-arturbosch-detekt" }
io-gitlab-arturbosch-detekt-detekt-rules-libraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "io-gitlab-arturbosch-detekt" }
javax-inject = "javax.inject:javax.inject:1"
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCio" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorSerializationKotlinxJson" }
material = { module = "com.google.android.material:material", version.ref = "material" }
org-jetbrains-dokka-dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
org-jetbrains-kotlin-compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
org-jetbrains-kotlinx-binary-compatibility-validator = { module = "org.jetbrains.kotlinx.binary-compatibility-validator:org.jetbrains.kotlinx.binary-compatibility-validator.gradle.plugin", version.ref = "org-jetbrains-kotlinx-binary-compatibility-validator" }
org-jetbrains-kotlinx-kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
org-jetbrains-kotlinx-kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
org-jetbrains-kotlinx-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
org-robolectric = "org.robolectric:robolectric:4.16"
se-eelde-toggles-toggles-core = { module = "se.eelde.toggles:toggles-core", version.ref = "se-eelde-toggles" }
se-eelde-toggles-toggles-flow = { module = "se.eelde.toggles:toggles-flow", version.ref = "se-eelde-toggles" }
se-eelde-toggles-toggles-prefs = { module = "se.eelde.toggles:toggles-prefs", version.ref = "se-eelde-toggles" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
com-android-lint = { id = "com.android.lint", version.ref = "agp" }
com-autonomousapps-dependency-analysis = "com.autonomousapps.dependency-analysis:3.4.1"
com-github-triplet-play = "com.github.triplet.play:3.12.2"
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "com-google-dagger" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-google-gms-google-services = "com.google.gms.google-services:4.4.4"
com-vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "com-vanniktech-maven-publish" }
com-vanniktech-maven-publish-base = { id = "com.vanniktech.maven.publish.base", version.ref = "com-vanniktech-maven-publish" }
io-gitlab-arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "io-gitlab-arturbosch-detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
org-jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlinx-binary-compatibility-validator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.18.1"
se-premex-gross = "se.premex.gross:0.4.6"
toggles-android-application = { id = "toggles.android.application" }
toggles-android-compose-application = { id = "toggles.android.compose.application" }
toggles-android-compose-module = { id = "toggles.android.compose.module" }
toggles-android-library = { id = "toggles.android.library" }
toggles-android-lint = { id = "toggles.android.lint" }
toggles-android-module = { id = "toggles.android.module" }
toggles-detekt-common = { id = "toggles.detekt.common" }
toggles-detekt-library = { id = "toggles.detekt.library" }
toggles-hilt = { id = "toggles.hilt" }
